# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_watchlist_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(298, 156)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label_Watchlist = QtWidgets.QLabel(Dialog)
        self.label_Watchlist.setGeometry(QtCore.QRect(10, 20, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_Watchlist.setFont(font)
        self.label_Watchlist.setStyleSheet("color: rgb(234, 230, 228);")
        self.label_Watchlist.setTextFormat(QtCore.Qt.RichText)
        self.label_Watchlist.setScaledContents(False)
        self.label_Watchlist.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Watchlist.setObjectName("label_Watchlist")
        self.lineEdit_NewWatchlistName = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_NewWatchlistName.setGeometry(QtCore.QRect(20, 50, 250, 31))
        self.lineEdit_NewWatchlistName.setStyleSheet("background-color: rgb(222, 220, 216);")
        self.lineEdit_NewWatchlistName.setCursorPosition(13)
        self.lineEdit_NewWatchlistName.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lineEdit_NewWatchlistName.setObjectName("lineEdit_NewWatchlistName")
        self.pushButton_Add = QtWidgets.QPushButton(Dialog)
        self.pushButton_Add.setGeometry(QtCore.QRect(120, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Add.setFont(font)
        self.pushButton_Add.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(234, 230, 228);")
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.pushButton_Cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(195, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Cancel.setFont(font)
        self.pushButton_Cancel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(234, 230, 228);")
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Watchlist"))
        self.label_Watchlist.setText(_translate("Dialog", "Name of the watchlist:"))
        self.lineEdit_NewWatchlistName.setText(_translate("Dialog", "New Watchlist"))
        self.pushButton_Add.setText(_translate("Dialog", "Add"))
        self.pushButton_Cancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
