# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_type_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(420, 207)
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.toolButton_alertAdd = QtWidgets.QToolButton(Form)
        self.toolButton_alertAdd.setGeometry(QtCore.QRect(59, 80, 140, 100))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_alertAdd.setFont(font)
        self.toolButton_alertAdd.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(234, 230, 228);")
        self.toolButton_alertAdd.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/addtype_alert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_alertAdd.setIcon(icon)
        self.toolButton_alertAdd.setIconSize(QtCore.QSize(64, 64))
        self.toolButton_alertAdd.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_alertAdd.setObjectName("toolButton_alertAdd")
        self.toolButton_alertAdd_2 = QtWidgets.QToolButton(Form)
        self.toolButton_alertAdd_2.setGeometry(QtCore.QRect(219, 80, 140, 100))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_alertAdd_2.setFont(font)
        self.toolButton_alertAdd_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(234, 230, 228);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/addtype_watch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_alertAdd_2.setIcon(icon1)
        self.toolButton_alertAdd_2.setIconSize(QtCore.QSize(64, 64))
        self.toolButton_alertAdd_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_alertAdd_2.setObjectName("toolButton_alertAdd_2")
        self.label_Alertlist = QtWidgets.QLabel(Form)
        self.label_Alertlist.setGeometry(QtCore.QRect(90, 28, 250, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Alertlist.setFont(font)
        self.label_Alertlist.setStyleSheet("color: rgb(234, 230, 228);")
        self.label_Alertlist.setTextFormat(QtCore.Qt.RichText)
        self.label_Alertlist.setScaledContents(False)
        self.label_Alertlist.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Alertlist.setObjectName("label_Alertlist")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Type"))
        self.toolButton_alertAdd.setText(_translate("Form", "Alert"))
        self.toolButton_alertAdd_2.setText(_translate("Form", "Watch"))
        self.label_Alertlist.setText(_translate("Form", "Type for new entry:"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
